//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuForm.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RegistForm
    {
        [DisplayName("東海")]
        [Range(1, 99, ErrorMessage = "屆數必須介於1~99之間")]
        public Nullable<int> Id { get; set; }

        [DisplayName("*姓名")]
        [Required(ErrorMessage = "姓名不可空白")]
        public string Name { get; set; }

        [DisplayName("*信箱")]
        [Required(ErrorMessage = "聯絡信箱姓名不可空白")]
        [EmailAddress(ErrorMessage = "E-Mail格式有誤")]
        public string Mail { get; set; }

        [DisplayName("*人數")]
        [Required(ErrorMessage = "人數不可空白")]
        [Range(1, 10, ErrorMessage = "人數必須介於1~10之間")]
        public int Total { get; set; }
       
        [Display(Name = "*已了解活動資訊")]
        [Range(typeof(bool), "true", "true", ErrorMessage = "請確認已了解活動資訊")]
        public bool IsActive { get; set; }

        [Display(Name = "備註")]
        public string Note { get; set; }

        public int DataID { get; set; }
    }
}
